# Generated by Django 4.2.4 on 2023-08-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('how', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trefle_id', models.PositiveIntegerField(unique=True)),
                ('common_name', models.CharField(blank=True, max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('author', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('rank', models.CharField(max_length=20)),
                ('family_common_name', models.CharField(max_length=100)),
                ('genus_id', models.PositiveIntegerField()),
                ('observations', models.TextField(blank=True)),
                ('vegetable', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True)),
                ('genus', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=100)),
                ('foliage_texture', models.CharField(blank=True, max_length=20)),
                ('foliage_color', models.CharField(blank=True, max_length=20)),
                ('leaf_retention', models.BooleanField(default=False)),
                ('fruit_conspicuous', models.BooleanField(default=False)),
                ('fruit_color', models.CharField(blank=True, max_length=20)),
                ('seed_persistence', models.BooleanField(default=False)),
                ('growth_form', models.CharField(blank=True, max_length=50)),
                ('growth_habit', models.CharField(blank=True, max_length=50)),
                ('growth_rate', models.CharField(blank=True, max_length=50)),
                ('nitrogen_fixation', models.CharField(blank=True, max_length=50)),
                ('shape_and_orientation', models.CharField(blank=True, max_length=50)),
                ('toxicity', models.CharField(blank=True, max_length=50)),
                ('ph_maximum', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('ph_minimum', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('light', models.PositiveIntegerField(null=True)),
                ('atmospheric_humidity', models.PositiveIntegerField(null=True)),
                ('soil_nutriments', models.PositiveIntegerField(null=True)),
                ('soil_salinity', models.PositiveIntegerField(null=True)),
                ('soil_texture', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
