# Generated by Django 4.2.4 on 2023-08-17 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('how', '0002_plant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='author',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='nitrogen_fixation',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='ph_maximum',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='ph_minimum',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='seed_persistence',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='status',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='toxicity',
        ),
        migrations.CreateModel(
            name='PlantPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.URLField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='how.plant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
